import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { Eye, EyeOff, KeyRound } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { supabase } from "@/integrations/supabase/client";
import { destinationForAccess, loadMyStaffAccess } from "@/hooks/useAdmin";

export const Route = createFileRoute("/reset-password")({ ssr: false, head: () => ({ meta: [{ title: "Reset password | BKS" }, { name: "description", content: "Securely choose a new password for your BKS account." }, { property: "og:title", content: "Reset your BKS password" }, { property: "og:description", content: "Secure BKS account recovery." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: ResetPasswordPage });
function ResetPasswordPage() { const navigate = useNavigate(); const [visible, setVisible] = useState(false); const [ready, setReady] = useState(false); const [loading, setLoading] = useState(false); useEffect(() => { const hash = new URLSearchParams(window.location.hash.slice(1)); setReady(hash.get("type") === "recovery" || hash.has("access_token")); }, []); async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const password = String(form.get("password")); if (password !== String(form.get("confirm"))) { toast.error("Passwords do not match"); return; } setLoading(true); const { error } = await supabase.auth.updateUser({ password }); setLoading(false); if (error) { toast.error("Password could not be updated", { description: error.message }); return; } toast.success("Password updated"); const access = await loadMyStaffAccess(); navigate({ to: destinationForAccess(access) }); } return <main className="grid min-h-screen place-items-center bg-muted/40 px-4"><div className="w-full max-w-md rounded-lg border bg-card p-7 shadow-soft"><span className="grid size-11 place-items-center rounded-lg bg-primary text-primary-foreground"><KeyRound /></span><h1 className="mt-5 font-display text-2xl font-bold">Choose a new password</h1><p className="mt-2 text-sm text-muted-foreground">Use at least eight characters and keep your account secure.</p>{ready ? <form className="mt-7 grid gap-4" onSubmit={submit}><div className="grid gap-2"><Label htmlFor="password">New password</Label><div className="relative"><Input id="password" name="password" type={visible ? "text" : "password"} minLength={8} required className="pr-10" /><Button type="button" variant="ghost" size="icon" className="absolute right-0 top-0" onClick={() => setVisible((v) => !v)} aria-label={visible ? "Hide password" : "Show password"}>{visible ? <EyeOff /> : <Eye />}</Button></div></div><div className="grid gap-2"><Label htmlFor="confirm">Confirm password</Label><Input id="confirm" name="confirm" type={visible ? "text" : "password"} minLength={8} required /></div><Button type="submit" variant="gold" size="lg" disabled={loading}>{loading ? "Updating…" : "Update password"}</Button></form> : <div className="mt-7 rounded-md bg-muted p-4 text-sm">This recovery link is invalid or has expired. <Link to="/auth" className="font-semibold underline">Request a new link</Link>.</div>}</div></main>; }